# Generated by Django 3.2.4 on 2021-10-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0007_alter_health_practitioner_health_practitioner'),
        ('aidApp', '0007_auto_20211007_0748'),
    ]

    operations = [
    ]
