# Generated by Django 3.2.4 on 2021-10-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0008_auto_20211012_0918'),
        ('aidApp', '0008_merge_20211011_1543'),
    ]

    operations = [
    ]
