# Generated by Django 3.2.4 on 2021-10-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0009_merge_20211012_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_status',
            field=models.IntegerField(default=0),
        ),
    ]
