# Generated by Django 3.2.4 on 2021-10-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0010_alter_appointment_app_status'),
        ('aidApp', '0012_alter_patient_d_o_b'),
    ]

    operations = [
    ]
