# Generated by Django 3.2.4 on 2021-10-20 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0013_merge_20211020_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='D_O_B',
            field=models.CharField(default=datetime.date(2021, 10, 20), max_length=20),
        ),
    ]
