# Generated by Django 3.2.4 on 2021-10-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0013_auto_20211021_1711'),
        ('aidApp', '0016_alter_patient_d_o_b'),
    ]

    operations = [
    ]
